version: '3'

services:
  scrapy:
    build:
      context: .
      dockerfile: ./scrapy/dockerfile
    volumes:
      - ./scrapy:/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017'
      MONGO_DATABASE: 'FFCK_BDD'

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: ./api/dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017'
      MONGO_DATABASE: 'FFCK_BDD'
    ports:
      - "8050:8050"
    command: python app.py
